- name: Back out any previous installations
  shell: echo 'y' | kubeadm reset

- name: Initilize the kubernetes master
  shell: >
    kubeadm init 
    --apiserver-advertise-address={{ ansible_host }}
    --pod-network-cidr={{ pod_network_cidr }}
    --ignore-preflight-errors 'ALL'
  register: kube_install
  changed_when: kube_install.rc == 0
  failed_when: "'Your Kubernetes control-plane has initialized successfully' not in kube_install.stdout"

- name: Setup root kubernetes session
  loop:
    - mkdir -p $HOME/.kube
    - rm -rf $HOME/.kube/*
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
  shell: "{{ item }}"

- name: Download the Calico install template
  get_url:
    url: https://docs.projectcalico.org/v3.10/manifests/calico.yaml
    dest: /tmp/calico.yaml

- name: Replace the pod CIDR in the Calico install template
  shell: sed -i -e "s?192.168.0.0/16?{{ pod_network_cidr }}?g" /tmp/calico.yaml

- name: Install the Calico CNI
  shell: kubectl apply -f /tmp/calico.yaml

- name: Download Helm install script
  get_url: 
    url: https://git.io/get_helm.sh
    dest: /tmp/get_helm.sh
    mode: 700

- name: Install Helm
  shell: /tmp/get_helm.sh
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already latest" not in result.stdout

- name: Install Tiller
  shell: /usr/local/bin/helm init
