- name: Ensure required variables are set
  assert:
    that:
      - vault.tick.influx_accounts.telegraf_user is defined
      - vault.tick.influx_accounts.telegraf_password is defined
      - vault.tick.telegraf.vcenter_host is defined
      - vault.tick.telegraf.vcenter_user is defined
      - vault.tick.telegraf.vcenter_password is defined

- name: Install the Telegraf package
  yum:
    name: telegraf
    state: present

- name: Start the telegraf service
  service:
    service: telegraf
    state: started
    enabled: yes

- name: Edit the telegraf config file
  no_log: true
  loop:
    # Influx credentials
    - section: "[outputs.influxdb]" # Module adds second set of brackets
      option: username
      value: "\"{{ vault.tick.influx_accounts.telegraf_user }}\""
    - section: "[outputs.influxdb]"
      option: password
      value: "\"{{ vault.tick.influx_accounts.telegraf_password }}\""
    # vSphere
    - section: "[inputs.vsphere]"
      option: vcenters
      value: "[ \"{{ vault.tick.telegraf.vcenter_host }}\" ]"
    - section: "[inputs.vsphere]"
      option: username
      value: "\"{{ vault.tick.telegraf.vcenter_user }}\""
    - section: "[inputs.vsphere]"
      option: password
      value: "\"{{ vault.tick.telegraf.vcenter_password }}\""
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "{{ item.section }}"
    option: "  {{ item.option }}"
    value: "  {{ item.value }}"
  register: telegraf_update_conf

- name: Restart Telegraf if config changed
  when: telegraf_update_conf is changed
  service:
    name: telegraf
    state: restarted
